---
defaults: &defaults
  build: .
  working_dir: /app
  volumes:
    - ".:/app"
  environment:
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - AWS_REGION
    - AWS_DEFAULT_REGION
    - AWS_SESSION_TOKEN

validate:
  <<: *defaults
  entrypoint: [bin/cfn-validate]
