---
defaults: &defaults
  build: .
  stdin_open: true
  working_dir: /app
  volumes:
    - ".:/app"
  environment:
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - AWS_REGION
    - AWS_DEFAULT_REGION
    - AWS_SESSION_TOKEN

cfn-aws-validate:
  <<: *defaults
  entrypoint: [cfn-aws-validate]

cfn-schema-validate:
  <<: *defaults
  entrypoint: [cfn-schema-validate]

cfn-order:
  <<: *defaults
  entrypoint: [cfn-order]

cfn-yamlify:
  <<: *defaults
  entrypoint: [cfn-yamlify]

cfn-jsonify:
  <<: *defaults
  entrypoint: [cfn-jsonify]

cfn-info:
  <<: *defaults
  entrypoint: [cfn-info]
