---
AWSTemplateFormatVersion: 2010-09-09
Resources:
  MyResource:
    Type: AWS::EC2::Instance
    Properties:
      UserData:
        Fn::Base64:
          Fn::Join: |
            #! /bin/bash

            This is a multiple line string
            that makes it easier to write scripts
            you can put %{{ATemplateReference}} in it and it will split
            it for you
      ImageId: ami-12345678
